version: "3"
services:
  app:
    build: .
    container_name: "itidigital-backend-challenge"
    restart: "no"
    ports:
      - 3333:3333
    environment:
      NODE_ENV: "production"
      APP_PORT: 3333
      MIN_LENGTH: 9
      MAX_LENGTH: 20
      MIN_DIGITS: 1
      MIN_UPPER: 1
      MIN_LOWER: 1
      MIN_SPECIAL: 1